pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "1234"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
               // git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
               git branch: 'main', url: 'https://github.com/KarthikPuvvada/Jenkins-Zero-To-Hero/'
           }
        }

        stage('Build Docker1'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t karthikpuvvada/ultimate-cicd:123 -f python-jenkins-argocd-k8s/Dockerfile .
                    '''
                }
            }
        }

       stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push karthikpuvvada/ultimate-cicd:123
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                //git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
               git branch: 'main', url: 'https://github.com/KarthikPuvvada/Jenkins-Zero-To-Hero/'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    //withCredentials([usernamePassword(credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                       // cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        sed -i '' "s/v1/123/g" python-jenkins-argocd-k8s/deploy/deploy.yaml
                      //  cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git add python-jenkins-argocd-k8s/deploy/deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/karthikpuvvada/Jenkins-Zero-To-Hero/python-jenkins-argocd-k8s.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
